/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prometheus metrics
         * @description Returns Prometheus exposition format (text/plain; version=0.0.4).
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transcription provider capabilities */
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maintenance/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger retention cleanup (runs + audio cache)
         * @description Runs best-effort retention cleanup based on environment configuration.
         *     Notes:
         *     - Never deletes transcripts under `output/<channelDir>/...`.
         *     - Deletes only API run persistence under `output/_runs/*` (if enabled) and old audio cache files under `audio/*`.
         */
        post: operations["triggerMaintenanceCleanup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get non-secret settings
         * @description Returns the current persisted non-secret defaults stored in `output/_settings.json`,
         *     and the effective config values after applying those settings to the loaded config.
         *     Notes:
         *     - Secrets are never returned here (e.g. `ASSEMBLYAI_API_KEY`, `Y2T_API_KEY`).
         *     - Precedence: `output/_settings.json` (lowest) < `config.yaml` < `.env` (highest).
         */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update non-secret settings
         * @description Updates persisted non-secret defaults in `output/_settings.json`.
         *     Send `null` for a key to clear it (remove it from the settings file).
         */
        patch: operations["patchSettings"];
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List watchlist entries */
        get: operations["listWatchlist"];
        put?: never;
        /** Add watchlist entry */
        post: operations["addWatchlistEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a local audio file
         * @description Uploads a local audio file and returns an `audioId` to use with `POST /runs`.
         *     The server stores uploads under `audio/_uploads` and metadata under `output/_uploads`.
         */
        post: operations["uploadAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get watchlist entry */
        get: operations["getWatchlistEntry"];
        put?: never;
        post?: never;
        /** Remove watchlist entry */
        delete: operations["removeWatchlistEntry"];
        options?: never;
        head?: never;
        /** Update watchlist entry */
        patch: operations["updateWatchlistEntry"];
        trace?: never;
    };
    "/scheduler/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get scheduler status */
        get: operations["getSchedulerStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduler/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start scheduler loop (in-process) */
        post: operations["startScheduler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduler/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop scheduler loop (in-process) */
        post: operations["stopScheduler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduler/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger one scheduler check cycle */
        post: operations["triggerSchedulerOnce"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream global events (SSE)
         * @description Server-Sent Events stream for global run updates. Event names include:
         *     - run:created
         *     - run:updated
         *     Data is JSON: { type, run, timestamp }.
         */
        get: operations["streamGlobalEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runs */
        get: operations["listRuns"];
        put?: never;
        /**
         * Create and start a run
         * @description Starts a run. For single-video URLs, the API is cache-first:
         *     if outputs already exist and `force` is false, the API returns a `done` run immediately (no transcription).
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan a run (enumerate + skip counts, no transcription)
         * @description Enumerates the input URL and computes how many videos are already processed vs remaining,
         *     without downloading audio or calling the transcription provider.
         */
        post: operations["planRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recent run events as JSON (tail)
         * @description Returns the most recent buffered run events as JSON.
         *     This is a convenience endpoint for debugging without SSE; it is not guaranteed to return the full history.
         */
        get: operations["getRunLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request cancellation of a run
         * @description Cooperative cancellation. If the run is running, the pipeline stops starting new work and ends as soon as practical.
         *     In-flight video work may finish. Queued runs are cancelled immediately.
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get artifacts for a run (channel videos listing) */
        get: operations["getRunArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream run events (SSE)
         * @description Server-Sent Events stream. Event names include:
         *     - run:start, run:done, run:cancelled, run:error
         *     - video:start, video:stage, video:done, video:skip, video:error
         */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List channels from output directory */
        get: operations["listLibraryChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/channels/{channelDirName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get channel metadata */
        get: operations["getLibraryChannelMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/channels/{channelDirName}/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List videos for a channel */
        get: operations["listLibraryVideos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/channels/{channelDirName}/videos/{basename}/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a specific video artifact */
        get: operations["getLibraryVideoArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
            message?: string;
        };
        OkResponse: {
            ok: boolean;
        };
        /**
         * @description Best-effort schema for pipeline events (SSE and persisted events).
         *     This is intentionally loose because the event payload varies by `type`.
         */
        PipelineEvent: {
            /**
             * @description Event type, e.g. `run:start`, `run:done`, `run:cancelled`, `run:error`,
             *     `video:start`, `video:stage`, `video:done`, `video:skip`, `video:error`.
             */
            type: string;
        } & {
            [key: string]: unknown;
        };
        CleanupResponse: {
            retention: {
                nowIso: string;
                runs: {
                    enabled: boolean;
                    days: number;
                    deleted: number;
                    kept: number;
                    errors: number;
                };
                audio: {
                    enabled: boolean;
                    days: number;
                    deletedFiles: number;
                    keptFiles: number;
                    errors: number;
                };
            };
        };
        ProviderCapability: {
            /** @enum {string} */
            id: "assemblyai" | "deepgram" | "openai_whisper";
            maxAudioBytes: number;
            supportsDiarization: boolean;
        };
        ProvidersListResponse: {
            providers: components["schemas"]["ProviderCapability"][];
        };
        /** @description Persisted non-secret defaults. Secrets (API keys) are never stored here. */
        NonSecretSettings: {
            /** @enum {string} */
            filenameStyle?: "id" | "id_title" | "title_id";
            /** @enum {string} */
            audioFormat?: "mp3" | "wav";
            /** @enum {string} */
            sttProvider?: "assemblyai" | "deepgram" | "openai_whisper";
            deepgramModel?: string;
            deepgramDiarization?: boolean;
            openaiWhisperModel?: string;
            maxAudioMB?: number;
            splitOverlapSeconds?: number;
            /** @enum {string} */
            languageDetection?: "auto" | "manual";
            languageCode?: string;
            concurrency?: number;
            maxNewVideos?: number;
            afterDate?: string;
            csvEnabled?: boolean;
            commentsEnabled?: boolean;
            commentsMax?: number;
            pollIntervalMs?: number;
            maxPollMinutes?: number;
            downloadRetries?: number;
            transcriptionRetries?: number;
            providerTimeoutMs?: number;
            catalogMaxAgeHours?: number;
        };
        SettingsGetResponse: {
            outputDir: string;
            settingsPath: string;
            updatedAt?: string;
            settings: components["schemas"]["NonSecretSettings"];
            effective: components["schemas"]["NonSecretSettings"];
            sources: {
                filenameStyle?: components["schemas"]["NonSecretSettingSource"];
                audioFormat?: components["schemas"]["NonSecretSettingSource"];
                sttProvider?: components["schemas"]["NonSecretSettingSource"];
                deepgramModel?: components["schemas"]["NonSecretSettingSource"];
                deepgramDiarization?: components["schemas"]["NonSecretSettingSource"];
                openaiWhisperModel?: components["schemas"]["NonSecretSettingSource"];
                maxAudioMB?: components["schemas"]["NonSecretSettingSource"];
                splitOverlapSeconds?: components["schemas"]["NonSecretSettingSource"];
                languageDetection?: components["schemas"]["NonSecretSettingSource"];
                languageCode?: components["schemas"]["NonSecretSettingSource"];
                concurrency?: components["schemas"]["NonSecretSettingSource"];
                maxNewVideos?: components["schemas"]["NonSecretSettingSource"];
                afterDate?: components["schemas"]["NonSecretSettingSource"];
                csvEnabled?: components["schemas"]["NonSecretSettingSource"];
                commentsEnabled?: components["schemas"]["NonSecretSettingSource"];
                commentsMax?: components["schemas"]["NonSecretSettingSource"];
                pollIntervalMs?: components["schemas"]["NonSecretSettingSource"];
                maxPollMinutes?: components["schemas"]["NonSecretSettingSource"];
                downloadRetries?: components["schemas"]["NonSecretSettingSource"];
                transcriptionRetries?: components["schemas"]["NonSecretSettingSource"];
                providerTimeoutMs?: components["schemas"]["NonSecretSettingSource"];
                catalogMaxAgeHours?: components["schemas"]["NonSecretSettingSource"];
            };
        };
        /** @enum {string} */
        NonSecretSettingSource: "env" | "config.yaml" | "settingsFile" | "default" | "unset";
        SettingsPatchRequest: {
            /** @description Partial settings update. Send `null` to clear a key. */
            settings: {
                /** @enum {string|null} */
                filenameStyle?: "id" | "id_title" | "title_id" | null;
                /** @enum {string|null} */
                audioFormat?: "mp3" | "wav" | null;
                /** @enum {string|null} */
                sttProvider?: "assemblyai" | "deepgram" | "openai_whisper" | null;
                deepgramModel?: string | null;
                deepgramDiarization?: boolean | null;
                openaiWhisperModel?: string | null;
                maxAudioMB?: number | null;
                splitOverlapSeconds?: number | null;
                /** @enum {string|null} */
                languageDetection?: "auto" | "manual" | null;
                languageCode?: string | null;
                concurrency?: number | null;
                maxNewVideos?: number | null;
                afterDate?: string | null;
                csvEnabled?: boolean | null;
                commentsEnabled?: boolean | null;
                commentsMax?: number | null;
                pollIntervalMs?: number | null;
                maxPollMinutes?: number | null;
                downloadRetries?: number | null;
                transcriptionRetries?: number | null;
                providerTimeoutMs?: number | null;
                catalogMaxAgeHours?: number | null;
            };
        };
        WatchlistEntry: {
            id: string;
            channelUrl: string;
            channelId?: string;
            channelTitle?: string;
            intervalMinutes?: number;
            enabled: boolean;
            lastCheckedAt?: string;
            lastRunId?: string;
            createdAt: string;
        };
        WatchlistCreateRequest: {
            /** @description YouTube channel or playlist URL (watchlist is for recurring sources, not single videos). */
            channelUrl: string;
            intervalMinutes?: number | null;
            enabled?: boolean;
        };
        WatchlistUpdateRequest: {
            /** @description Optional. Set to null to clear override and use the scheduler global default. */
            intervalMinutes?: number | null;
            enabled?: boolean;
        };
        WatchlistEntryResponse: {
            entry: components["schemas"]["WatchlistEntry"];
        };
        WatchlistListResponse: {
            entries: components["schemas"]["WatchlistEntry"][];
        };
        SchedulerStatus: {
            enabled: boolean;
            running: boolean;
            intervalMinutes: number;
            maxConcurrentRuns: number;
            lastTickAt?: string;
            nextTickAt?: string;
        };
        SchedulerStatusResponse: {
            status: components["schemas"]["SchedulerStatus"];
        };
        SchedulerTriggerResponse: {
            result: {
                checked: number;
                runsCreated: number;
            };
            status: components["schemas"]["SchedulerStatus"];
        };
        HealthResponse: {
            ok: boolean;
            service: string;
            version?: string;
            deps?: {
                ytDlp?: {
                    ok: boolean;
                    version?: string;
                    error?: string;
                };
                ffmpeg?: {
                    ok: boolean;
                    error?: string;
                };
                disk?: {
                    ok: boolean;
                    freeBytes?: number;
                    freeGb?: number;
                    error?: string;
                };
                persist?: {
                    ok: boolean;
                    dir: string;
                    writable: boolean;
                    error?: string;
                };
            };
        };
        /** @enum {string} */
        RunStatus: "queued" | "running" | "done" | "error" | "cancelled";
        RunStats: {
            succeeded: number;
            failed: number;
            skipped: number;
            total: number;
        };
        RunRecord: {
            /** Format: uuid */
            runId: string;
            status: components["schemas"]["RunStatus"];
            inputUrl: string;
            force: boolean;
            createdAt: string;
            startedAt?: string;
            finishedAt?: string;
            cancelRequested?: boolean;
            error?: string;
            callbackUrl?: string;
            channelId?: string;
            channelTitle?: string;
            channelDirName?: string;
            previewVideoId?: string;
            previewTitle?: string;
            stats?: components["schemas"]["RunStats"];
        };
        RunsResponse: {
            runs: components["schemas"]["RunRecord"][];
        };
        RunGetResponse: {
            run: components["schemas"]["RunRecord"];
        };
        RunCreateRequest: {
            url?: string;
            /** @description Audio ID returned by `POST /audio`. */
            audioId?: string;
            force?: boolean | null;
            /**
             * @description Limit this run to at most N NEW (unprocessed) videos.
             *     Applied AFTER skipping already-processed videos so repeated runs can backfill incrementally.
             */
            maxNewVideos?: number | null;
            /** @description Only include videos after YYYY-MM-DD (best-effort; based on yt-dlp upload_date). */
            afterDate?: string | null;
            /**
             * @description Optional. If set, the API sends a POST webhook when the run ends:
             *     - `run:done` when status becomes done
             *     - `run:error` when status becomes error
             *     - `run:cancelled` when status becomes cancelled
             *     If `Y2T_WEBHOOK_SECRET` is set on the server, requests include:
             *     - `X-Y2T-Timestamp` (ISO)
             *     - `X-Y2T-Signature` (HMAC-SHA256 of `${timestamp}.${body}`)
             */
            callbackUrl?: string | null;
            config?: {
                [key: string]: unknown;
            };
        } & (unknown | unknown);
        RunPlanRequest: {
            url: string;
            force?: boolean | null;
            /**
             * @description Limit this run to at most N NEW (unprocessed) videos.
             *     Applied AFTER skipping already-processed videos so repeated runs can backfill incrementally.
             */
            maxNewVideos?: number | null;
            /** @description Only include videos after YYYY-MM-DD (best-effort; based on yt-dlp upload_date). */
            afterDate?: string | null;
            config?: {
                [key: string]: unknown;
            };
        };
        AudioUploadMeta: {
            audioId: string;
            title: string;
            originalFilename: string;
            contentType?: string;
            bytes: number;
            ext: string;
            createdAt: string;
        };
        AudioUploadResponse: {
            audio: components["schemas"]["AudioUploadMeta"];
        };
        RunCreateLinks: {
            run: string;
            events: string;
            artifacts: string;
            cancel: string;
        };
        RunCreateResponse: {
            run: components["schemas"]["RunRecord"];
            links: components["schemas"]["RunCreateLinks"];
        };
        PlannedVideo: {
            id: string;
            title: string;
            url: string;
            uploadDate?: string;
            basename: string;
            processed: boolean;
        };
        RunPlan: {
            inputUrl: string;
            force: boolean;
            channelId: string;
            channelTitle?: string;
            totalVideos: number;
            alreadyProcessed: number;
            /** @description Total unprocessed videos under the given filters (may be larger than `toProcess` when `maxNewVideos` is set). */
            unprocessed: number;
            toProcess: number;
            filters: {
                afterDate?: string;
                maxNewVideos?: number;
            };
            videos: components["schemas"]["PlannedVideo"][];
            /** @description Videos selected to be processed for this run (unprocessed + capped by `maxNewVideos`). */
            selectedVideos: components["schemas"]["PlannedVideo"][];
        };
        RunPlanResponse: {
            plan: components["schemas"]["RunPlan"];
        };
        ChannelInfo: {
            channelId: string;
            channelTitle?: string;
            channelDirName: string;
            channelThumbnailUrl?: string;
            metaPath?: string;
        };
        ChannelsResponse: {
            channels: components["schemas"]["ChannelInfo"][];
        };
        ChannelMeta: {
            channelId: string;
            channelTitle: string;
            channelUrl: string;
            retrievedAt?: string;
        };
        ChannelMetaResponse: {
            channelDirName: string;
            meta: components["schemas"]["ChannelMeta"];
        };
        OutputPaths: {
            jsonPath: string;
            txtPath: string;
            mdPath: string;
            jsonlPath: string;
            csvPath: string;
            commentsPath: string;
            metaPath: string;
            channelMetaPath: string;
            errorLogPath: string;
            audioPath: string;
        };
        VideoMeta: {
            videoId: string;
            title: string;
            url: string;
            uploadDate?: string;
            description?: string;
            channelId: string;
            channelTitle?: string;
            /** @enum {string} */
            source?: "youtube" | "upload";
            audioId?: string;
            originalFilename?: string;
            /** @enum {string} */
            filenameStyle: "id" | "id_title" | "title_id";
            audioFormat: string;
            languageCode?: string;
            languageDetection?: boolean;
            languageConfidence?: number;
            createdAt: string;
        };
        VideoInfo: {
            videoId: string;
            title?: string;
            basename: string;
            metaPath?: string;
            paths: components["schemas"]["OutputPaths"];
            meta?: components["schemas"]["VideoMeta"];
        };
        VideosResponse: {
            channelDirName: string;
            videos: components["schemas"]["VideoInfo"][];
        };
        /** @enum {string} */
        ArtifactKind: "txt" | "md" | "json" | "jsonl" | "meta" | "comments" | "csv" | "audio";
        RunArtifacts: {
            channelDirName?: string;
            channelId?: string;
            channelTitle?: string;
            videos: components["schemas"]["VideoInfo"][];
        };
        RunArtifactsResponse: {
            run: components["schemas"]["RunRecord"];
            artifacts: components["schemas"]["RunArtifacts"];
        };
    };
    responses: {
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                /** @description Seconds until the rate limit window resets */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        RunId: string;
        ChannelDirName: string;
        Basename: string;
        ArtifactKind: components["schemas"]["ArtifactKind"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    triggerMaintenanceCleanup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsGetResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patchSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsGetResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listWatchlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addWatchlistEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistEntryResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    uploadAudio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @description Optional title for the audio run. */
                    title?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioUploadResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request timed out */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getWatchlistEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistEntryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeWatchlistEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    updateWatchlistEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistEntryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getSchedulerStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatusResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startScheduler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatusResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    stopScheduler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatusResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    triggerSchedulerOnce: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerTriggerResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    streamGlobalEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: {
                /** @description When true, returns a best-effort deep health check (deps + disk + persistence). Requires X-API-Key unless Y2T_HEALTH_DEEP_PUBLIC=true. */
                deep?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    planRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunPlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPlanResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunGetResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRunLogs: {
        parameters: {
            query?: {
                /** @description Max events to return (default 200, max 2000). */
                tail?: number;
            };
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run: components["schemas"]["RunRecord"];
                        events: {
                            id: number;
                            event: components["schemas"]["PipelineEvent"];
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunGetResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getRunArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunArtifactsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listLibraryChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLibraryChannelMeta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelDirName: components["parameters"]["ChannelDirName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelMetaResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listLibraryVideos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelDirName: components["parameters"]["ChannelDirName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideosResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLibraryVideoArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelDirName: components["parameters"]["ChannelDirName"];
                basename: components["parameters"]["Basename"];
                kind: components["parameters"]["ArtifactKind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
